2025-08-06 14:22:15,095 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:31:00,908 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:31:05,072 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:42:03,178 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 14:44:14,423 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:48:04,600 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - BatchRunner inicializado com 15 CIAs disponíveis
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - Iniciando processamento para 1 CIAs e competência 01-2025
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - CIAs selecionadas: ['Bradesco']
2025-08-06 14:48:59,954 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-06 14:48:59,955 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-06 14:48:59,963 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-06 14:48:59,964 - extrato_app.CoreData.batch_runner - INFO - Todas as CIAs informadas já possuem conta virtual gerada para essa competência. Gerando resumo mesmo assim.
2025-08-06 14:48:59,965 - extrato_app.CoreData.batch_runner - INFO - Iniciando geração de resumo final para competência 01-2025
2025-08-06 14:48:59,966 - extrato_app.CoreData.batch_runner - INFO - Verificando se já existe geração para as CIAs na competência 01-2025
2025-08-06 14:48:59,967 - extrato_app.CoreData.batch_runner - INFO - Executando query: SELECT 1 FROM cont_prod_bare WHERE competencia = '01-2025' LIMIT 1;
2025-08-06 14:48:59,970 - extrato_app.CoreData.batch_runner - WARNING -  Já foi gerado Conta Virtual para Bradesco na competência 01-2025
2025-08-06 14:48:59,971 - extrato_app.CoreData.batch_runner - INFO - Consultando resumo para 1 CIAs (solicitadas + geradas anteriormente)
2025-08-06 14:56:41,459 - django.request - WARNING - Not Found: /atualizar-caixa
2025-08-06 15:00:40,989 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 15:00:50,909 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:00:53,518 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:01:00,475 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:03:11,785 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:04:59,069 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:05:41,895 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 15:50:49,503 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 15:51:35,267 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 15:53:38,728 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:07:14,365 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:09:59,095 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:33:03,197 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:33:17,198 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:34:07,517 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:35:19,524 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:35:25,914 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:36:52,382 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:37:04,825 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:37:42,878 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 16:38:11,423 - django.request - WARNING - Not Found: /favicon.ico
2025-08-06 16:38:57,247 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:40:48,016 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 16:41:08,561 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\urls.py changed, reloading.
2025-08-06 16:41:26,417 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:49:45,206 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:49:46,940 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:51:13,154 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:51:19,606 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:53:27,911 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:53:29,827 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 16:57:14,295 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 17:01:32,483 - django.utils.autoreload - INFO - C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py changed, reloading.
2025-08-06 17:01:35,472 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:08,950 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:02:08,997 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:27,240 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:02:27,260 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:15,085 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:04:15,119 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:18,465 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:18,498 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:20,304 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:04:32,533 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:04:32,570 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:30,147 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:30,171 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:33,128 - django.request - ERROR - Internal Server Error: /executar-atualizar-caixa
Traceback (most recent call last):
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bruno.cassio\Documents\GitHub\extrado_based\extrado_based\extrato_app\extrato_app\views.py", line 150, in executar_atualizar_caixa
    return render(request, 'extrato_app/caixa_resultado.html', {
        'existing': existing,
    ...<3 lines>...
        'mes': mes,
    })
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bruno.cassio\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: extrato_app/caixa_resultado.html
2025-08-06 17:09:33,157 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:35,895 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
2025-08-06 17:09:35,905 - django.request - WARNING - Not Found: /.well-known/appspecific/com.chrome.devtools.json
